void selectionSort(int arreglo[], int n);
void insertionSort(int a[], int n);
void HeapSort(int a[], int n);
void BuildHeap(int* A, int size);
void Heapify(int* A, int i, int size);
int partition (int arr[], int low, int high);
void quickSort(int arr[], int low, int high);
void bubbleSort(int a[], int size);
void merge(int list[], int p, int q, int r, int c, char * s);
void mergeSort(int list[], int p, int r, int i, char * s);
